core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("pages.urls")),
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("gigs/", include("gigs.urls")),
    path("orders/", include("orders.urls")),
    path("dashboard/", include("dashboard.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gigs/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.gig_index, name="gig_index"),
    # path("<int:gig_id>", views.gig_view, name="gig_info"),
    path("create_gig", views.create_gig, name="create_gig"),
    path("category/<int:category_id>", views.show_category, name="category"),
    path("orders/", include("orders.urls")),
    path("approve/", views.comment_aprove, name="approve"),
    path("<int:gigid>/edit", views.edit_gig, name="edit_gig"),
    path("plan/edit/<int:planid>/", views.edit_plan, name="edit_plan"),
    path("<int:pk>", views.GigDetail.as_view(), name="gig_detail"),
    path("add_comment", views.AddComment.as_view(), name="add_comment"),
    path("add_plan", views.AddPlan.as_view(), name="add_plan"),
    # path("add_image", views.add_image, name="add_image"),
]

gigs/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Best Practice for getting the user model
User = get_user_model()


# This a model that hanndels advertisment for intrested user
# to be shown to other users
class Gig(models.Model):
    title = models.CharField(max_length=255, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey("gigs.Category", on_delete=models.SET_NULL, null=True, blank=True)
    sub_category = models.ForeignKey("gigs.SubCategory", on_delete=models.SET_NULL, null=True, blank=True)
    description = models.TextField()
    experience = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return f"{self.user.user_name} {self.title} gig"

    def get_showcase(self):
        showcase = ShowcaseImage.objects.filter(gig=self)
        img = showcase.first().image
        if img.name == "scimages/default.jpg" and len(showcase) >= 2:
            img = showcase[1].image
        return img

    def get_lowest_plan_price(self):
        plan_price_list = []
        for plan in self.plan_set.all():
            plan_price_list.append(plan.price)
        if len(plan_price_list) > 0:
            return min(plan_price_list)
        return 0

    def plans_count(self):
        return self.plan_set.count()


# Every gig has a category and you can choose one
# from database of this model
class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.name}"


# Every gig has a category and you can choose one
# from database of this model
class SubCategory(models.Model):
    category = models.ForeignKey("gigs.Category", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.category} - {self.name}"


# every gig have one or more plans that can be
# used to advertise different tier of services
class Plan(models.Model):
    gig = models.ForeignKey("gigs.Gig", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    price = models.PositiveIntegerField(default=5000)
    feature_list = models.TextField()

    def __str__(self):
        return f"gig #{self.gig.id} plan"


# a gig can have some comments
class Comment(models.Model):
    gig = models.ForeignKey("gigs.Gig", on_delete=models.CASCADE)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    body = models.CharField(max_length=255)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.user_name} on gig #{self.gig.id}"


# every gig can have multiple images that showcase the user work
class ShowcaseImage(models.Model):
    gig = models.ForeignKey("gigs.Gig", on_delete=models.CASCADE)
    image_meta = models.CharField(max_length=50)
    image = models.ImageField(upload_to="scimages", default="scimages/default.jpg")

    def __str__(self):
        return f"#{self.id}"

    @staticmethod
    def get_images(gig):
        photo = ShowcaseImage.objects.filter(gig=gig)
        if photo[0].image.name == "scimages/default.jpg" and len(photo) >= 2:  # delete default pic from image showcase
            photo = photo[1:]
        return photo


# This model class handels ratings for a gig
class UserRate(models.Model):
    gig = models.ForeignKey("gigs.Gig", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return f"#{self.id}"

gigs/forms.py
from django import forms
from .models import Gig, Plan, ShowcaseImage, Comment


class GigCreationForm(forms.ModelForm):
    """
    Form for add Gig
    """

    class Meta:
        model = Gig
        fields = ["title", "category", "description", "experience"]
        exclude = ["user"]


class ShowcaseForm(forms.ModelForm):
    """
    Form for add Gig
    """

    class Meta:
        model = ShowcaseImage
        fields = ["image"]
        exclude = ["gig"]


class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea, max_length=400, required=False)

    class Meta:
        model = Comment
        fields = ["title", "body"]
        exclude = ["gig", "user", "is_aproved"]


class PlanForm(forms.ModelForm):
    """
    Form for add Plans
    """

    class Meta:
        model = Plan
        fields = ["title", "price", "feature_list"]
        exclude = ["gig"]


class GigEditForm(forms.ModelForm):
    """
    Form for edit Gig
    """

    class Meta:
        model = Gig
        fields = ["title", "description", "experience"]
        exclude = ["user"]


class PlanEditForm(forms.ModelForm):
    """
    Form for edit Plans
    """

    class Meta:
        model = Plan
        fields = ["title", "price", "feature_list"]
        exclude = ["gig"]

gigs/views.py
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from .forms import GigCreationForm, GigEditForm, ShowcaseForm, CommentForm, PlanForm, PlanEditForm
from django.http.response import Http404
from django.shortcuts import redirect, render
from .models import Comment, Gig, Plan, ShowcaseImage
from django.core.exceptions import PermissionDenied
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

# Create your views here.
def gig_index(request):
    gigs = Gig.objects.all()
    context = {"gigs": gigs}
    return render(request, "gigs/index.html", context=context)


class GigDetail(generic.DetailView):
    model = Gig
    template_name = "gigs/gig.html"
    extra_context = {}

    def get(self, *args, **kwargs):
        super().get(self, *args, **kwargs)
        gig = Gig.objects.get(id=self.kwargs["pk"])
        photo = ShowcaseImage.get_images(gig=gig)
        self.extra_context.update({"photo": photo})
        return super().get(self, *args, **kwargs)


class AddComment(generic.CreateView, LoginRequiredMixin):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        gig_id = self.request.GET.get("gig")
        gig = Gig.objects.get(id=gig_id)
        form.save(commit=False).user = self.request.user
        form.save(commit=False).gig = gig
        form.save()
        return redirect("gig_detail", gig_id)


class AddPlan(generic.CreateView, LoginRequiredMixin):
    model = Plan
    form_class = PlanForm

    def form_valid(self, form):
        gig_id = self.request.GET.get("gig")
        gig = Gig.objects.get(id=gig_id)
        form.save(commit=False).gig = gig
        form.save()
        return redirect("gig_detail", gig_id)

    def get(self, request, *args, **kwargs):
        gig_id = self.request.GET.get("gig")
        gig = Gig.objects.get(id=gig_id)
        if request.user == gig.user:
            return super().get(request, *args, **kwargs)
        raise PermissionDenied


# def add_image(request, gig_id):
#     try:
#         gig = Gig.objects.get(id=gig_id)
#         img_formset = modelformset_factory(ShowcaseImage, form=ShowcaseForm, extra=5)
#         photo = ShowcaseImage.get_images(gig)
#         if request.method == "POST":
#             formset = img_formset(request.POST, request.FILES, queryset=ShowcaseImage.objects.none())
#             p_form = PlanForm(request.POST)
#             c_form = CommentForm(request.POST)
#             if c_form.is_valid():
#                 c_form.save(commit=False).user = request.user
#                 c_form.save(commit=False).gig = gig
#                 c_form.save()
#                 return redirect("gig_info", gig_id=gig.id)
#             if p_form.is_valid():
#                 p_form.save(commit=False).gig = gig
#                 p_form.save()
#                 return redirect("gig_info", gig_id=gig.id)
#             if formset.is_valid():
#                 for form in formset:
#                     form.save(commit=False).gig = gig
#                     form.save()
#                 return redirect("gig_info", gig_id=gig.id)

#         else:
#             p_form = PlanForm()
#             c_form = CommentForm()
#             formset = img_formset(queryset=ShowcaseImage.objects.none())

#     except Gig.DoesNotExist:
#         raise Http404("Gig not found")

#     return render(
#         request,
#         "gigs/gig.html",
#         context={
#             "gig": gig,
#             "c_form": c_form,
#             "p_form": p_form,
#             "formset": formset,
#             "photo": photo,
#         },
#     )


@login_required
def create_gig(request):
    if request.method == "POST":
        g_form = GigCreationForm(request.POST)
        img_form = ShowcaseForm(request.POST, request.FILES)
        if g_form.is_valid() and img_form.is_valid():
            g_form.save(commit=False).user = request.user
            gig = g_form.save()
            img_form.save(commit=False).gig = gig
            img_form.save()
            return redirect("gig_detaile", pk=gig.id)
    else:
        g_form = GigCreationForm()
        img_form = ShowcaseForm()

    return render(request, "gigs/create_gig.html", context={"g_form": g_form, "img_form": img_form})


def show_category(request, category_id):
    try:
        gigs = Gig.objects.filter(category__id=category_id)
        context = {"gigs": gigs}
        return render(request, "gigs/category.html", context=context)
    except Gig.DoesNotExist:
        raise Http404("there is no gig in this category")


@csrf_exempt
@require_POST
def comment_aprove(request):
    cid = request.POST["id"]
    comment = Comment.objects.get(id=cid)
    comment.is_approved = True
    comment.save()
    return redirect("gig_detail", pk=comment.gig.id)


@login_required
def edit_gig(request, gigid):
    gig = Gig.objects.get(id=gigid)
    if gig.user != request.user:
        raise PermissionDenied
    if request.method == "POST":
        form = GigEditForm(request.POST, instance=gig)
        if form.is_valid():
            form.save()
            return redirect("gig_detail", gig_id=gigid)
    else:
        form = GigEditForm(instance=gig)
    return render(request, "gigs/gig_edit.html", context={"form": form, "gig": gig})


@login_required
def edit_plan(request, planid):
    plan = Plan.objects.get(id=planid)
    if plan.gig.user != request.user:
        raise PermissionDenied
    if request.method == "POST":
        form = PlanEditForm(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            return redirect("gig_detail", pk=plan.gig.id)
    else:
        form = PlanEditForm(instance=plan)
    return render(request, "gigs/edit_plan.html", context={"form": form, "plan": plan})

gigs/templates/gigs/category.html
{% extends "pages/base.html" %}
{% block title %}Gigs{% endblock %}
{% block body %}
<div class='mt-5 lg:grid grid-cols-2 xl:grid-cols-5 gap-3 mx-20'>
  {% for gig  in gigs  %}
  <div class="flex flex-col justify-between bg-brand-card mb-3 pb-4 rounded-md">
    <div class="">
      <img class="w-full" src="{{gig.get_showcase.url}}" alt="" style="height: 150px;object-fit: cover;">
      <div class="flex flex-col px-3 flex-grow mt-3">
        <div class="">
          <div class="flex items-center space-x-2 mb-2">
            <img class="rounded-full" src="{{gig.user.profile.profile_pic.url}}" alt="" style="width:35px; height: 35px; object-fit: cover;">
            <div>
              <p class="font-thin">{{gig.user.user_name}}</p>
              <p class="text-sm opacity-60">Level {{gig.experience}} Freelancer</p>
            </div>
          </div>
          <a href="{% url 'gig_detail' gig.id %}" style="-webkit-line-clamp: 2;text-overflow: ellipsis;overflow: hidden;display: -webkit-box;-webkit-box-orient: vertical;word-wrap: break-word;"><h3 class="font-serif text-lg">{{gig.title}}</h3></a>
          <small class="bg-blue-600 px-2 pb-0.5 text-white rounded-full text-opacity-80">{{gig.category}}</small>
        </div>
      </div>   
    </div>
    <div class="px-3 mt-2">
      <i class="fa fa-star text-yellow-500"></i><span class="ml-1 text-yellow-500">4.6 </span><span class="text-sm opacity-60">(129)</span>
      <hr>
      <div class="flex justify-between items-center">
        <p class="text-sm">starting at <span class="text-lg">{{gig.get_lowest_plan_price}}$</span></p>
        <div class="">
          <a class="ml-1" href="#"><i class="fas fa-bell"></i></a>
          <a class="ml-1" href="#"><i class="fas fa-bell"></i></a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

gigs/templates/gigs/comment_form.html
{%extends "pages/base.html"%}
{% block body %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
<form  method="post" style="padding-top:50px; width:400px" class='mx-auto' enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Confirm</button>
</form>
{%endblock%}

gigs/templates/gigs/create_gig.html
{% extends "pages/base.html" %}
{% block title %}Gigs{% endblock %}
{% block body %}
    {% load crispy_forms_tags %}
    {% load tailwind_filters %}
    {% csrf_token %}
    <div class="mx-auto mb-5">
        <form  method="post" style="padding-top:50px; width:400px;height:100%" class='container' enctype="multipart/form-data">
            {{g_form|crispy}}
            {{img_form|crispy}}
        <button type="submit" class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Confirm</button>
        </form>   
    </div>
{% endblock %}

gigs/templates/gigs/edit_plan.html
{% extends "pages/base.html" %}
{% block title %}{{plan.title}} edit {% endblock %}
{% block body %}
{% csrf_token %}
	{% load crispy_forms_tags %}
    {% load tailwind_filters %}
    <div class="mx-auto mb-5">
        <form  method="post" style="padding-top:50px; width:400px;" class='md:container md:mx-auto' enctype="multipart/form-data">
            <h1 class = 'font-thin text-2xl' style='text-align:center ; padding-bottom:50px'>Edit plan </h1>
            {% csrf_token %}
            {{ form|crispy}}
            <button type="submit" class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' >Confirm</button>
        </form>
    </div>
    

{% endblock %}

gigs/templates/gigs/gig.html
{% extends "pages/base.html" %}
{% block head %}
<script src="https://kit.fontawesome.com/d6eba2497b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}{{gig}}{% endblock %}
{% block body %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}

<div class="mx-8 mt-10">
  
  <!-- Info -->
  <div>
    <p class="text-center text-2xl mb-4">{{object.title}}</p>
    <div class="mx-auto mb-3 w-10/12 p-5 bg-brand-card rounded-md">
      <p>{{object.description}}</p>
    </div>
    <div class="mx-auto">
        <div class="mx-auto">
          <img src="{{photo.first.image.url}}" class="mx-auto" style="width: 50%;">
        </div>
    </div>
  </div>
  <!-- Info -->

  <!--Plans-->
  <div class="flex mt-10">
    <div class="mx-auto grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3">
      {% for plan in object.plan_set.all %}
        <div class="relative bg-white py-6 px-6 rounded-3xl w-64 my-4 shadow-xl">
          <div class="text-white flex items-center absolute rounded-full py-4 px-4 shadow-xl bg-pink-500 left-4 -top-6">
            <!-- svg  -->
            <svg xmlns="http://www.w3.org/2000/svg" class="h-8 w-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z" />
            </svg>
          </div>
          <div class="mt-8">
            <p class="text-xl font-semibold my-2">{{plan.title}}</p>
            <div class="flex space-x-2 text-black-400 text-sm">
              <p>{{plan.feature_list}}</p>
            </div>
            <div class="flex space-x-2 text-gray-400 text-sm my-3">
              <p>owner : {{plan.gig.user.user_name}}</p>
            </div>
            <div class="border-t-2"></div>

            <div class="flex justify-between">
              <div class="my-2">
                <p class="font-semibold text-base mb-2">Price:</p>
                <div class="text-base text-gray-400 font-semibold">
                  <p>{{plan.price}} $</p>
                </div>
              </div>
            </div>
            <div class="my-2">
              <a class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" href="{% url 'order' %}?plan={{plan.id}}&gig={{plan.gig.id}}">Order</a>
              {% if user == plan.gig.user %} <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'edit_plan' plan.id %}">Edit</a>{% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
      </div>
  </div>
  <!--Plans-->
  
  <!--Comments-->
  <div class="mx-10">
    <h1 class="text-xl font-semibold">Comments</h1>
    {% for comment in object.comment_set.all %}
        {% if comment.is_approved %}
          <div class="bg-brand-card rounded-md w-80 my-4">
            <h5 class="bg-white text-lg font-serif">{{comment.user.user_name}}</h3>
            <p class="font-bold">{{comment.title}}<p>
            <h6>{{comment.body}}</h5>
          </div>
        {% endif %}
    {% endfor %}
    <!--Add Comment-->
    {% if user.is_authenticated %}
      <h1>Write a comment</h1>
      <a href="{% url 'add_comment' %}?gig={{object.id}}">add</a>
    {% else %}
      <p>You have to <a href="{% url 'login' %}?next_page={{request.path}}">login<a> to your account first<p>   
    {% endif %}
  </div>
  <!-- Comments -->
</div>
<script>
  function showCreatePlanCard() {
    var x = document.getElementById("CreatePlanCard");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
  function showAddImageCard() {
    var x = document.getElementById("AddImageCard");
    if (x.style.display === "none") {
      x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>
{% endblock %}

gigs/templates/gigs/gig_edit.html
{% extends "pages/base.html" %}
{% block title %}{{gig.title}} edit {% endblock %}
{% block body %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
<div class="mx-auto mb-5">
    <form  method="post" style="padding-top:50px; width:400px;" class='md:container md:mx-auto' enctype="multipart/form-data">
        <h1 class = 'font-thin text-2xl' style='text-align:center ; padding-bottom:50px'>Edit Gig</h1>
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' >Confirm</button>      
    </form>
</div>
{% endblock %}

gigs/templates/gigs/index.html
{% extends "pages/base.html" %}
{% block title %}Gigs{% endblock %}
{% block body %}
<div class='mt-5 lg:grid grid-cols-2 xl:grid-cols-5 gap-3 mx-20'>
  {% for gig  in gigs  %}
  <div class="flex flex-col justify-between bg-brand-card mb-3 pb-4 rounded-md">
    <div class="">
      <img class="w-full" src="{{gig.get_showcase.url}}" alt="" style="height: 150px;object-fit: cover;">
      <div class="flex flex-col px-3 flex-grow mt-3">
        <div class="">
          <div class="flex items-center space-x-2 mb-2">
            <img class="rounded-full" src="{{gig.user.profile.profile_pic.url}}" alt="" style="width:35px; height: 35px; object-fit: cover;">
            <div>
              <p class="font-thin">{{gig.user.user_name}}</p>
              <p class="text-sm opacity-60">Level {{gig.experience}} Freelancer</p>
            </div>
          </div>
          <a href="{% url 'gig_detail' gig.id %}" style="-webkit-line-clamp: 2;text-overflow: ellipsis;overflow: hidden;display: -webkit-box;-webkit-box-orient: vertical;word-wrap: break-word;"><h3 class="font-serif text-lg">{{gig.title}}</h3></a>
          <small class="bg-blue-600 px-2 pb-0.5 text-white rounded-full text-opacity-80">{{gig.category}}</small>
        </div>
      </div>   
    </div>
    <div class="px-3 mt-2">
      <i class="fa fa-star text-yellow-500"></i><span class="ml-1 text-yellow-500">4.6 </span><span class="text-sm opacity-60">(129)</span>
      <hr>
      <div class="flex justify-between items-center">
        <p class="text-sm">starting at <span class="text-lg">{{gig.get_lowest_plan_price}}$</span></p>
        <div class="">
          <a class="ml-1" href="#"><i class="fas fa-bell"></i></a>
          <a class="ml-1" href="#"><i class="fas fa-bell"></i></a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>    
{% endblock %}

gigs/templates/gigs/plan_form.html
{%extends "pages/base.html"%}
{% block body %}
{% load crispy_forms_tags %}
{% load tailwind_filters %}
<form  method="post" style="padding-top:50px; width:400px;" class='mx-auto' enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Confirm</button>
</form>
{%endblock%}